### ISSUE TITLE
bug: possible missing events

### ISSUE THREAD

**Issue by bonustrack** [checkpoint-labs/checkpoint#48] opened 2022-06-08 08:40 UTC
It happen 2 time in production that the deploy event was not triggered for sx-api, not sure what's the reason would require more debugging.

**Comment by Sekhmet** [comment] 2023-06-06 14:52
Can be reopened if we see it again (if not dupe of https://github.com/checkpoint-labs/checkpoint/issues/185)

**Closed by Sekhmet** 2023-06-06 14:52 UTC
Labels: bug
